### ISSUE TITLE
Trong - BE: Test cases for update user feature

### ISSUE THREAD

**Issue by ToLazyToCode** [DKhoa-fpt/Diamond-Shop-System-SWP391-SE1840-Group6#18]
Code a test using Junit 5 framework to test UpdateUser by ADMIN feature

**Comment by ToLazyToCode** [comment]
Done! Waiting for response

**Comment by UpperMoon0** [comment]
Need update user feature for the "USER" role as well. Customers should be able to update some of their profile information.

**Comment by ToLazyToCode** [comment]
On it
